### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by dcryptoniun** [dcryptoniun/Wind-Tails#1]
The README.md file is important for any project as it provides essential information about the project, such as its purpose, installation instructions, usage guidelines, and contribution guidelines. However, the current README.md file is outdated and needs to be updated to reflect the current state of the project.

Proposed solution: Create a new branch for the project and update the README.md file to include the following information:

1. Project overview: Briefly describe the project and its purpose.

2. Installation instructions: A step-by-step guide on installing and setting up the project on a local machine. add both npm and yarn commands

3. Usage guidelines: A detailed explanation of how to use the project and its features.

4. Contribution guidelines: Guidelines on how to contribute to the project, including information on code style, issue reporting, and pull requests.

5. License information: A statement on the license under which the project is released.

**Comment by yash-seth** [comment]
Hey, I'd like to take this up.

**Comment by dcryptoniun** [comment]
> Hey, I'd like to take this up.

Yeah, sure. Go for it!

**Comment by yash-seth** [comment]
Hey, I've added in the updated readme as part of PR #3 . Have a look and let me know if any other changes are needed. Cheers!

**Comment by dcryptoniun** [comment]
thanks @yash-seth for your contribution.
